### ISSUE TITLE
Update Electron to it's latest version?

### ISSUE THREAD

**Issue by max-programming** [arturssmirnovs/parluks#2]
This is a very nice project and I would love updating `electron` here because it's outdated and updating actually **increased performance**.
I worked on it and resolved every error and issue after updating. 
I get only one error which is a problem with Electron maybe but it does not seem to collide with the overall app. Everything works fine on my end.

![image](https://user-images.githubusercontent.com/51731966/104277334-aa2bf080-54cc-11eb-8cd4-988582b86957.png)

**Comment by arturssmirnovs** [comment]
Thanks for participating in this project as well :) 
I will take a look at your pull request soon..  

This is really nice project idea for sure.. This will help ton of developers to inspect responsive design easily..
